project:
  type: book

execute: 
  echo: true
  warning: false
  include: true
  freeze: auto

book:
  title: "Data Analysis using R"
  subtitle: "including what they forgot to teach you about computers"
  author: "Emma Rand"
  date: "16/10/2022"
  site-url: "https://3mmarand.github.io/combio/"
  chapters:
    - index.qmd
    - intro.qmd
    - file_systems.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo
      dark: solar
  pdf:
    documentclass: scrreprt

editor: visual

